config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "cameras#index"

  get 'dashboard', to: 'dashboard#index'
  get 'profiles', to: 'profiles#update'

  get 'bookings/index'
  get 'bookings/show'


  resources :cameras do
    resources :bookings, only: [:create, :new]
  end
  resources :bookings, only: [:edit, :update, :index]
  resources :categories, only: [:index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :camera
end

app/models/camera.rb
class Camera < ApplicationRecord
  belongs_to :user
  # belongs_to :category
  has_many :bookings, dependent: :destroy
  has_one_attached :picture

  CATEGORIES = ['DSLR', 'Mirrorless', 'Bridge', 'Compact', 'Action', 'Instant', '360 Cameras']

end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cameras, dependent: :destroy
  has_many :bookings
  has_many :bookings_as_owner, through: :cameras, source: :bookings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_booking, only: [:show, :edit, :update]
  before_action :set_camera, only: [:new, :create]

  before_action :authenticate_user!

  def index
    @bookings = current_user.bookings
    @bookings_as_owner = current_user.bookings_as_owner
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.camera = @camera
    @booking.user = current_user
    if @booking.save
      redirect_to camera_path(@camera)
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if params[:status] == "false"
      @booking.update(status: false)
    elsif params[:status] == "true"
      @booking.update(status: true)
    else
      @booking.update(booking_params)
    end
    redirect_to cameras_path
  end


  private

  def set_camera
    @camera = Camera.find(params[:camera_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :finish_date)
  end
end

app/controllers/cameras_controller.rb
class CamerasController < ApplicationController
  before_action :set_camera, only: [:show, :edit, :update, :destroy]

  def index
    @cameras = Camera.all
    @categories = Camera.pluck(:category).uniq
    if params[:query].present?
      @cameras = Camera.where("name ILIKE ?", "%#{params[:query]}%")
    end
  end

  def show
    @camera = Camera.find(params[:id])
  end

  def new
    @camera = Camera.new
  end

  def create
    @camera = Camera.new(camera_params)
    @camera.user = current_user
    if @camera.save
      redirect_to camera_path(@camera)
    else
      render :new
    end
  end

  def edit
    @camera = Camera.find(params[:id])
  end

  def update
    @camera = Camera.find(params[:id])
    @camera.update(camera_params)
    redirect_to cameras_path
  end

  def destroy
    @camera = Camera.find(params[:id])
    @camera.destroy
    redirect_to dashboard_path
  end

  private

  def set_camera
    @camera = Camera.find(params[:id])
  end

  def camera_params
    params.require(:camera).permit(:name, :details, :category, :price, :year, :model, :picture_url, :picture)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @cameras = Camera.where(category: params[:format])
    @category = params[:format]
  end

  def show
    @cameras = Camera.where(category: params[:format])
    @category = params[:format]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @user = current_user
    @bookings = current_user.bookings
    @bookings_as_owner = current_user.bookings_as_owner
    @cameras = current_user.cameras
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @cameras = Camera.all
    @categories = Category.all
    @categories = Camera.pluck(:category).uniq
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: :update

  def update
    if @user.update(user_params)
      flash[:notice] = "Your profile has been updated"
      redirect_to dashboard_path
    else
      render :update
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<h1>Booking Details</h1>

<p><strong>For Camera:</strong> Booking n<%= @booking.id %> </p>
<p><strong>From User:</strong> <%= @booking.user.first_name %> <%= @booking.user.last_name %></p>


<%= link_to "Approve", booking_path(@booking, status: "true"), data: {turbo_method: :patch} %>
<%= link_to "Deny", booking_path(@booking, status: "false"), data: {turbo_method: :patch} %>

app/views/bookings/index.html.erb
<h1>My Bookings</h1>

<% @bookings.each do |booking| %>
  <p>Booking n*<%= booking.id %></p>
  <p><%= booking.camera.name %></p>
  <p><%= booking.user.first_name %> <%= booking.user.last_name %></p>
  <p>From <%= booking.start_date %></p>
  <p>To <%= booking.finish_date %></p>
<% end %>

<h2>My booked cameras</h2>

<% @bookings_as_owner.each do |booking| %>
  <p>Booking n*<%= booking.id %></p>
  <p><%= booking.camera.name %></p>
  <p><%= booking.user.first_name %> <%= booking.user.last_name %></p>
  <p>From <%= booking.start_date %></p>
  <p>To <%= booking.finish_date %></p>
<% end %>

app/views/bookings/new.html.erb
<%= simple_form_for [@camera, @booking] do |f| %>
  <%= f.input :start_date,
               as: :string,
               input_html: {data: {controller: "datepicker"} } %>
  <%= f.input :finish_date,
               as: :string,
               input_html: {data: {controller: "datepicker"} } %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/bookings/show.html.erb
<h1>My booking</h1>

<p><%= @booking.id %></p>
<p><%= @booking.user_id %></p>
<p><%= @booking.start_date %></p>
<p><%= @booking.end_date %></p>

app/views/bookings/update.html.erb
<h1>Booking Details</h1>

<p><strong>For Camera:</strong> Booking n-<%= @booking.id %> for <%= @camera.name %></p>
<p><strong>From User:</strong> <%= @booking.user.first_name %> <%= @booking.user.last_name %></p>

<% if @booking.status == true %>
  <%= link_to "Approve", cameras_path %>
  <%= link_to "Deny", booking_path(@booking, status: "false"), method: :patch %>
<% end %>

app/views/cameras/booking.html.erb
<h1>Booking Details</h1>

<p><strong>For Camera:</strong> Booking n-<%= @booking.id %> for <%= @camera.name %></p>
<p><strong>From User:</strong> <%= @booking.user.first_name %> <%= @booking.user.last_name %></p>

<% if @booking.status == true %>
  <%= link_to "Approve", approve_booking_path(@booking)%>
  <%= link_to "Deny", deny_booking_path(@booking.update), method: :put %>
<% end %>

app/views/cameras/edit.html.erb
<h1>Edit Camera</h1>

<%= simple_form_for @camera do |f| %>
  <div class="form-group">
    <%= f.input :name %><br>
    <%= f.input :details %><br>
    <%= f.input :year %><br>
    <%= f.input :model %><br>
    <%= f.input :category %><br>
    <%= f.input :price %>
  </div>

  <div>
    <%= f.submit "Update Camera" %>

    <%= link_to "Delete", camera_path(@camera), data: {turbo_method: :delete, turbo_confirm: "Delete #{@camera.name}?"} %>
  </div>
<% end %>

app/views/cameras/index.html.erb
<div class="camera-index-flex">
  <div class="cat-list">
  <% @categories.each do |category| %>
    <%= link_to category, categories_path(category), class: "cat-btn" %>
  <% end %>
  </div>
  <div class="cameras-container">
    <ul class="cameras-cards cameras-box">
      <% @cameras.each do |camera| %>
        <li>
        <div class= "cameras-pic" >
          <%= link_to cl_image_tag(camera.picture.key), camera_path(camera)%>
          </div>
          <div class="cameras-info">
            <p><%= link_to camera.name, camera_path(camera), class:"cameras-name"%> - <strong><%= camera.model %></strong></p>
          </div>
          <div>
            <%= camera.price %>€
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/cameras/new.html.erb
<%= simple_form_for @camera do |f| %>
  <%= f.input :name %>
  <%= f.input :details %>
  <%= f.input :category, collection: Camera::CATEGORIES %>
  <%= f.input :price %>
  <%= f.input :year %>
  <%= f.input :model %>
  <%= f.input :picture, as: :file%>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>
<br>
<%= link_to "Go back to dashboard", dashboard_path, class: 'btn btn-primary' %>

app/views/cameras/show.html.erb
<div class="camera-details-flex">
    <h1 class="camera-name"><%= @camera.name %> | <%= @camera.model %></h1>
  <div class="camera-details">
    <%= cl_image_tag(@camera.picture.key)%>
    <div class="details-right">
      <h4><%= @camera.category %></h4>
      <p><%= @camera.year %></p> <br>
      <p><%= @camera.details %></p> <br>
      <br>
      <h6>Rent me for: <%= @camera.price %>€/day</h6><br>
    </div>
  </div>
  <div class="link-buttons">
    <%= link_to "Go back to category", categories_path(@camera.category), class: 'cat-btn-small' %>
    <%= link_to "Book this camera", new_camera_booking_path(@camera), class: 'cat-btn' %>
    <%= link_to "Go back to homepage", root_path, class: 'cat-btn-small' %>
  </div>
</div>

app/views/categories/index.html.erb
<h1> <%= @category %></h1>
<div class="cameras-container">
  <ul class="cameras-cards cameras-box">
    <% @cameras.each do |camera| %>
      <li>
        <%= link_to cl_image_tag(camera.picture.key), camera_path(camera)%>
        <div class="cameras-info">
          <%= link_to camera.name, camera_path(camera), class:"cameras-name"%>
          <%= link_to camera.price, camera_path("#"), class:"cameras-price"%>€ <br>
        </div>
      </li>
    <% end %>
  </ul>
  <div class="link-buttons">
    <%= link_to "Go back to homepage", root_path, class: 'cat-btn-category' %>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="body-dash">
  <h1 class="container text-center">Hello <%= @user.first_name %>!</h1>

  <div class="my-cameras-container list-type-column">
    <h1>My Cameras</h1>
    <ul class="cameras-cards cameras-box">
      <% @cameras.each do |camera| %>
        <li>
          <%= cl_image_tag(camera.picture.key, :height=>200, :width=>200, :crop=>"fill") %>
          <div class="cameras-info">
            <%= link_to camera.name, camera_path(camera), class:"cameras-name"%>
            <%= link_to camera.price, camera_path("#"), class:"cameras-price"%>€ <br>
          </div>
          <div class="card-body">
            <%= link_to "Edit", edit_camera_path(camera), class: 'cat-btn cat-btn-small cat-btn-edit' %>
            <%= link_to "Delete", camera_path(camera), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'cat-btn cat-btn-small cat-btn-delete' %>
          </div>
        </li>
      <% end %>
    </ul>
    <%= link_to "Add a camera", new_camera_path(@camera), class: 'cat-btn cat-btn-cut btn-centered' %>
  </div>

  <div class="bookings">
    <div class="bookings-container list-type-row">
      <h1 class="container text-center">My Booked Cameras</h1>
      <% @bookings.each do |booking| %>
      <div class="card mb-3" style="max-width: 540px;">
        <div class="row no-gutters">
          <div class="col-md-4">
            <%= cl_image_tag(booking.camera.picture.key, :height=>180, :width=>180, :crop=>"fill") %>
          </div>
          <div class="col-md-8">
            <h5 class="card-title"><strong><%= booking.camera.name %> <%= booking.camera.model %></strong></h5>
            <p class="card-text">Owner: <%= booking.user.first_name %> <%= booking.user.last_name %></p>
            <p class="card-text">From: <%= booking.start_date %></p>
            <p class="card-text">To: <%= booking.finish_date %></p>
            <p class="card-text"><small class="text-muted">Booking reference number: <%= booking.id %></small></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>


    <div class="bookings-container list-type-row">
        <h1 class="container text-center">My Bookings</h1>
        <% @bookings_as_owner.each do |booking| %>
        <div class="card mb-3" style="max-width: 540px;">
          <div class="row no-gutters">
            <div class="col-md-4">
              <%= cl_image_tag(booking.camera.picture.key, :height=>180, :width=>180, :crop=>"fill") %>
            </div>
            <div class="col-md-8">
              <h5 class="card-title"><strong><%= booking.camera.name %> <%= booking.camera.model %></strong></h5>
              <p class="card-text">User: <%= booking.user.first_name %> <%= booking.user.last_name %></p>
              <p class="card-text">From: <%= booking.start_date %></p>
              <p class="card-text">To: <%= booking.finish_date %></p>
              <p class="card-text"><small class="text-muted">Booking reference number: <%= booking.id %></small></p>
            </div>
          </div>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CameraCartel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="page-container">
      <div class="navbar-container"><%= render "shared/navbar" %></div>
      <div class="content-container"><%= yield %></div>
      <div class="footer-container"><%= render "shared/footer" %></div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Camera Cartel</h1>

<% @categories.each do |category| %>
<%= link_to category, category_path(category) %>
<% end %>
<br>
<ul>
  <% @cameras.each do |camera| %>
    <li>
      <%= link_to camera.name, camera_path(camera) %> <br>
    </li>
  <% end %>
</ul>

app/views/profiles/update.html.erb
<h1>Profile#update</h1>
<p>Find me in app/views/profile/update.html.erb</p>
<%= simple_form_for @user, profiles_path(@user), html: { method: :patch } do |f| %>
  <%= f.error_notification %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.submit 'Save changes', class: 'btn btn-primary' %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer rounded">
  <div class="footer-links text-center">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright text-center">
    📸 Thank you for visiting CameraCartel 📸
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="flex-div-brand">
    <%= link_to root_path ,class: "navbar-brand" do %>
      <%= image_tag("https://res.cloudinary.com/dh5wteizg/image/upload/v1706887474/mepl7u4vsv6cwmppkicy.png") %>
    <% end %>
    </div>
    <%= form_tag cameras_path, method: :get, class: 'd-flex flex-grow-1 justify-content-center' do %>
      <%= text_field_tag :query, params[:query], placeholder: "Search for a camera", class: "form-control me-2 search-border" %>
      <%= submit_tag "Search", class: "search-btn" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/jule-tech", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Edit account", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "user-login" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>